# Generated by Django 5.0.6 on 2024-06-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_subcategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'v_category_subcategory',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=100)),
                ('author', models.CharField(default='Unknown', max_length=50)),
                ('published_date', models.DateField()),
                ('category_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.category_subcategory')),
            ],
        ),
    ]
