# Generated by Django 5.0.6 on 2024-06-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scrap', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('last_scrap_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category_subcategory')),
            ],
        ),
    ]
