# Generated by Django 5.0.6 on 2024-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='v_subcategory',
        ),
    ]
